### ISSUE TITLE
SCRIPT5009: 'MyPaLoaded' is undefined (Edge)

### ISSUE THREAD

**Issue by remcotolsma** [myparcelnl/woocommerce-myparcel#18]
Hello WooCommerce MyParcel developers,

On Microsoft Edge version `38.14393.0.0` we get the following error which results in not loading the `#myparcel-iframe` iframe:

```
SCRIPT5009: 'MyPaLoaded' is undefined
```

![schermafbeelding 2017-03-08 om 11 13 27](https://cloud.githubusercontent.com/assets/869674/23700105/1ed1b602-03f2-11e7-92ae-bf42ad8ea511.png)

We use version `2.1.3` of the WooCommerce MyParcel plugin.

The `/wp-content/plugins/woocommerce-myparcel/assets/js/wcmp-frontend.js?ver=2.1.3` file which defines the `MyPaLoaded` function is loaded correctly.

https://github.com/myparcelnl/woocommerce-myparcel/blob/v2.1.3/assets/js/wcmp-frontend.js#L27-L31

It is working correctly in the following browsers:

* Google Chrome » `56.0.2924.87 (64-bit)`
* Firefox » `51.0.1`
* Safarai » `10.0.3 (12602.4.8)`

Is this something you can reproduce and fix?

```
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393
```

![schermafbeelding 2017-03-08 om 11 13 46](https://cloud.githubusercontent.com/assets/869674/23700125/34c34b38-03f2-11e7-96ed-32791498bac1.png)

I saw there was also a support topic on WordPress.org about issues on mobile devices:
https://wordpress.org/support/topic/plugin-not-loading-on-mobile-devices/

But it look likes like version `v2.1.4-beta1` is not fixing this issue.
https://github.com/myparcelnl/woocommerce-myparcel/releases/tag/v2.1.4-beta1

**Comment by remcotolsma** [comment]
Also created a WordPress.org support topic:
https://wordpress.org/support/topic/script5009-mypaloaded-is-undefined-edge/

**Comment by Spreeuw** [comment]
Thanks for reporting. I cannot reproduce this in two separate development sites (different ISPs) in Edge 38.14393.0.0. Is this in Windows on mobile or desktop (since you are referring to a thread about mobile?).

All previous issues with iPhone and iPad (=Safari) are resolved, apart from an issue with the width rendering on mobile (wider than the canvas). We are looking into this issue, but AFAIK this is only an issue in Safari on iOS and does not prevent the iframe from loading.

Can you rule out theme or plugin conflicts? Do you use server side caching or CDN (like Cloudflare)?

**Comment by remcotolsma** [comment]
I'm testing this with VirtualBox / Windows 10 dekstop. We use the WordPress [WP Rocket](https://wp-rocket.me/) plugin for caching, but i disabled most features. And since it is working on browsers like Google Chrome, Firefox and Safari i don't think it is a caching issue. You can test it yourself by placing a order on https://be-slank.nl/. The WooCommerce MyParcel component is only displayed for orders below < € 51,-.

**Comment by Spreeuw** [comment]
I can reproduce the issue on that site but not on two of my own test sites, so I suspect a plugin or theme conflict (I would still disable caching to be sure we can rule that out).

Can you try with one of the default WP themes? If that doesn't resolve the issue, can you try to rule out plugin conflicts? Let me know what you find!

**Comment by Spreeuw** [comment]
@remcotolsma any news on this issue?

**Comment by Spreeuw** [comment]
@remcotolsma I have reviewed this issue again and pinned it down to a race condition. To prevent the race condition I have chosen a solution that dynamically creates the iframe so that the script has full control over the load order of elements and other scripts. Can you test 2.3.0 Beta 3? https://github.com/myparcelnl/woocommerce-myparcel/releases/tag/v2.3.0-beta-3

**Comment by remcotolsma** [comment]
Thanks, we just installed `v2.3.0-beta-3` on https://be-slank.nl/, i currently can't test on Edge but hope the issue is fixed.

**Comment by Spreeuw** [comment]
@remcotolsma I just checked be-slank.nl in edge, but unfortunately the problem only seems to have gotten worse. The whole page now reloads and then crashes. No further information from Edge about what causes the crash/reload 😞

**Comment by Spreeuw** [comment]
Seems like an actual bug in Edge itself, related to the html5 `<template>` tag.
[Beta 4](https://github.com/myparcelnl/woocommerce-myparcel/releases/tag/v2.3.0-beta-4) fixes this (patch applied to be-slank.nl too!)

**Comment by remcotolsma** [comment]
Thanks for the check and quick fix, hope the issue is now fixed :).
